apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=106403001296.dkr.ecr.us-east-1.amazonaws.com/frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.platform: linux/amd64
spec:
  project: default
  source:
    repoURL: ssh://APKARRRQ46PIDQBSW4YZ@git-codecommit.us-east-1.amazonaws.com/v1/repos/devops-blueprint-eks-frontend
    targetRevision: main
    path: k8s
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
