apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: backend
  namespace: argocd
spec:
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: backend
      images:
        - alias: backend
          imageName: 106403001296.dkr.ecr.us-east-1.amazonaws.com/backend
          commonUpdateSettings:
            updateStrategy: newest-build
