apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: frontend
  namespace: argocd
spec:
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: frontend
      images:
        - alias: frontend
          imageName: 106403001296.dkr.ecr.us-east-1.amazonaws.com/frontend
          commonUpdateSettings:
            updateStrategy: newest-build
