---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-secrets
  namespace: backend
spec:
  provider: aws
  secretObjects:
    - secretName: backend-secrets
      type: Opaque
      data:
        - objectName: DB_HOST
          key: DB_HOST
        - objectName: DB_NAME
          key: DB_NAME
        - objectName: DB_USER
          key: DB_USER
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: AWS_REGION
          key: AWS_REGION
        - objectName: S3_BUCKET
          key: S3_BUCKET
  parameters:
    usePodIdentity: "true"
    region: us-east-1
    objects: |
      - objectName: "test-eks-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DB_HOST"
            objectAlias: "DB_HOST"
          - path: "DB_NAME"
            objectAlias: "DB_NAME"
          - path: "DB_USER"
            objectAlias: "DB_USER"
          - path: "DB_PASSWORD"
            objectAlias: "DB_PASSWORD"
          - path: "AWS_REGION"
            objectAlias: "AWS_REGION"
          - path: "S3_BUCKET"
            objectAlias: "S3_BUCKET"
